/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF, useTexture } from '@react-three/drei';

export default function ModelScene(props) {
	const { nodes, materials } = useGLTF('/donuts.glb');

	const bakedTexture = useTexture([
		'/bake-donuts-1.jpg',
		'/bake-donuts-2.jpg',
		'/bake-room.jpg',
		'/bake-objects.jpg',
	]);

	bakedTexture.forEach((e) => (e.flipY = false));

	const [donutTexture, donutTexture2, planeTexture, objectsTexture] =
		bakedTexture;
	return (
		<group {...props} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane.geometry}
				material={nodes.Plane.material}
				position={[-0.091, 0.002, -0.001]}
				scale={2.037}>
				<meshBasicMaterial map={planeTexture} />
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle.geometry}
				material={nodes.Circle.material}
				position={[0.021, 0.006, -0.028]}>
				<meshBasicMaterial map={planeTexture} />
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={nodes.Cube.material}
				position={[-0.185, 0.388, 0.094]}
				scale={0.386}>
				<meshBasicMaterial map={objectsTexture} />
			</mesh>
			{/* <mesh
				castShadow
				receiveShadow
				geometry={nodes.Filter.geometry}
				material={nodes.Filter.material}
				position={[0.205, 0.253, -0.452]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={[0.691, 0.38, 0.25]}
			/> */}
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.potted_plant_04002.geometry}
				material={nodes.potted_plant_04002.material}
				position={[-0.447, 0.002, 0.388]}
				rotation={[Math.PI, -0.206, Math.PI]}
				scale={0.571}>
				<meshBasicMaterial map={objectsTexture} />
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.UtensilsJar001_utensil08.geometry}
				material={nodes.UtensilsJar001_utensil08.material}
				position={[-0.379, 0.084, -0.303]}
				rotation={[0, 0.402, 0]}
				scale={0.705}>
				<meshBasicMaterial map={objectsTexture} />
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutLeft.geometry}
				material={nodes.DonutLeft.material}
				position={[-0.007, 0.026, 0.038]}>
				<meshBasicMaterial map={donutTexture} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing.geometry}
					material={nodes.Icing.material}>
					<meshBasicMaterial map={donutTexture} />
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutRight.geometry}
				material={nodes.DonutRight.material}
				position={[0.014, 0.024, -0.096]}>
				<meshBasicMaterial map={donutTexture2} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing001.geometry}
					material={nodes.Icing001.material}>
					<meshBasicMaterial map={donutTexture2} />
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutRight001.geometry}
				material={nodes.DonutRight001.material}
				position={[-0.012, 0.074, -0.082]}
				rotation={[-3.097, 0.798, 3.079]}>
				<meshBasicMaterial map={donutTexture2} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing002.geometry}
					material={nodes.Icing002.material}>
					<meshBasicMaterial map={donutTexture2} />
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutRight002.geometry}
				material={nodes.DonutRight002.material}
				position={[0.005, 0.125, -0.065]}
				rotation={[0.071, 0.428, 0]}>
				<meshBasicMaterial map={donutTexture2} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing003.geometry}
					material={nodes.Icing003.material}>
					<meshBasicMaterial map={donutTexture2} />
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutLeft001.geometry}
				material={nodes.DonutLeft001.material}
				position={[-0.015, 0.076, 0.039]}
				rotation={[0, 1.15, 0]}>
				<meshBasicMaterial map={donutTexture} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing004.geometry}
					material={nodes.Icing004.material}>
					<meshBasicMaterial map={donutTexture} />
				</mesh>
			</mesh>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.DonutFront.geometry}
				material={nodes.DonutFront.material}
				position={[0.087, 0.054, -0.025]}
				rotation={[-3.109, 0.248, -2.426]}>
				<meshBasicMaterial map={donutTexture} />
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Icing005.geometry}
					material={nodes.Icing005.material}>
					<meshBasicMaterial map={donutTexture} />
				</mesh>
			</mesh>
		</group>
	);
}

useGLTF.preload('/donuts.glb');
